### ISSUE TITLE
Documentation shows wrong example

### ISSUE THREAD

**Issue by Vlix** [cheopslab/lazy-cache#3]
In `System.Cache` the following snippet is found in the `main` function of the example at the top of the module:

```haskell
let cachedTimeout = Cache.mkCached cache i -> do
         threadDelay $ i * 1_000_000
         pure i
 ```
 
 This is probably wrong because this used to be `Cache.createIO` (or `mkCached` used to have the type `createIO` has right now).

So this either should be changed to `Cache.createIO cache \i -> do` or the entire example should be rewritten to use the current `mkCached` function.

(As a bonus, change the `\i ->` to `\\i ->` in the example, so haddock doesn't throw the backslash away)

**Comment by qnikst** [comment]
Thanks a lot! Fixed an example, will upload new documentation to Hackage ASAP!
